/**
 * Auto-generated sidebar: derives structure from the docs/ directory tree,
 * so regenerating docs never breaks navigation with missing-id errors.
 * Section labels/order come from _category_.json files in each directory.
 */
module.exports = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};
